//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileUpload.EFEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileUpload
    {
        public int FileId { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileUploadedUserId { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
